services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lzu_store
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-db: